version: '3.9'

services:
  # frontend:
  #   build:
  #     context: .
  #     dockerfile: front/Dockerfile
  #   ports:
  #     - "80:80"
  #   networks:
  #     - app-network

   backend:
    build:
      context: .
      dockerfile: torrentCreator/Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
