on:
  push:
    branches:
      - main
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Installer OpenSSH si nécessaire
      run: |
        if ! command -v ssh-agent >/dev/null; then
          sudo apt-get update && sudo apt-get install -y openssh-client
        else
          echo "ssh-agent est déjà installé."
        fi
      
    - name: Configure l'agent SSH
      env:
        SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
      run: |
        eval "$(ssh-agent -s)"
        echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh
        ssh-keyscan 85.31.239.153 >> ~/.ssh/known_hosts
        chmod 644 ~/.ssh/known_hosts
        ssh root@85.31.239.153 "hostname"
        cd ../
        ls
        scp -r TorrentEase/.dockerignore root@85.31.239.153:/home/TorrentEase
        ssh root@85.31.239.153 "cd /home/TorrentEase && ls && cd front && sudo rm -rf node_modules && npm i  && npm run build && sudo systemctl restart nginx &&  cd .. && cd torrentCreator && ls && sudo rm -rf node_modules &&  npm i && printf "IP=85.31.239.153\nPORT=3001" > .env &&  screen -dmS mynodeapp node index.mjs"
